version: "3"

services:
  telegram-bot:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: make docker-run
    container_name: telegram_bot_template
    volumes:
      - ./code:/app/code
      - ./codegen:/app/codegen
      - ./data:/app/data
      - ./configs:/app/configs
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env