version: "3"

services:
  telegram-bot:
    image: ghcr.io/danila-initiative/${{vars.PROJECT_NAME}}:${GITHUB_SHA:-latest}
    restart: always
    command: make docker-run
    container_name: ${{vars.PROJECT_NAME}}
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
