name: Deploy production

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
      - run: docker build -t ghcr.io/$GITHUB_ACTOR/template-bot:latest -t ghcr.io/$GITHUB_ACTOR/template-bot:$GITHUB_SHA .
      - run: docker image push ghcr.io/$GITHUB_ACTOR/template-bot:$GITHUB_SHA
      - run: docker image push ghcr.io/$GITHUB_ACTOR/template-bot:latest
